#!/usr/bin/env python3
"""Generate the launcher's ROM-variant table from games/bt3/variants/*.json.

The variant descriptors are the single source of truth for serials, boot-ELF
hashes, titles, runner filenames and data directories. The launcher is a
standalone Qt app that cannot read the repository at runtime, so its table is
generated into the build tree at configure time and included by
launcher_window.cpp. deploy.py reads the same descriptors for the runner names
it bundles.

    gen_variant_table.py <variants-dir> <output.inc>

Only descriptors with a "launcher" block are emitted, in canonical-first order:
a variant nobody has built a runner for has nothing to select.
"""
import argparse
import json
import sys
from pathlib import Path

CANONICAL = "SLUS_216.78"


def descriptors(variants_dir: Path) -> list[dict]:
    found = []
    for path in sorted(variants_dir.glob("*.json")):
        item = json.loads(path.read_text())
        serial = item.get("serial")
        if not serial or "launcher" not in item:
            continue
        launcher = item["launcher"]
        missing = [k for k in ("label", "runner", "data_dir") if not launcher.get(k)]
        if missing:
            raise ValueError(f"{path}: launcher block is missing {', '.join(missing)}")
        if not item.get("boot_elf_sha256"):
            raise ValueError(f"{path}: a launcher profile needs boot_elf_sha256")
        found.append(item)
    if not found:
        raise ValueError(f"no launcher-capable descriptors in {variants_dir}")
    found.sort(key=lambda i: (i["serial"] != CANONICAL, i["serial"]))
    if found[0]["serial"] != CANONICAL:
        raise ValueError(f"{CANONICAL} must be present and first")
    return found


def render(items: list[dict]) -> str:
    lines = [
        "// Generated by tools/gen_variant_table.py from games/bt3/variants/*.json.",
        "// Do not edit: change the descriptor and reconfigure.",
        "// clang-format off",
        "namespace {",
        "struct VariantRecord",
        "{",
        "    const char *id;",
        "    const char *label;",
        "    const char *bootName;",
        "    const char *runnerName;",
        "    const char *dataRelative;",
        "    const char *expectedSha256;",
        "    bool selfExtracting;",
        "};",
        "",
        "constexpr VariantRecord kVariantRecords[] = {",
    ]
    for item in items:
        launcher = item["launcher"]
        lines.append("    {")
        lines.append(f'        "{item["serial"]}",')
        lines.append(f'        "{launcher["label"]}",')
        lines.append(f'        "{item["serial"]}",')
        lines.append(f'        "{launcher["runner"]}",')
        lines.append(f'        "{launcher["data_dir"]}",')
        lines.append(f'        "{item["boot_elf_sha256"]}",')
        lines.append(f'        {"true" if launcher.get("self_extracting") else "false"},')
        lines.append("    },")
    lines += [
        "};",
        "} // namespace",
        "// clang-format on",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("variants_dir", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        text = render(descriptors(args.variants_dir))
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    # Write only on change so a reconfigure does not force a launcher rebuild.
    if not args.output.is_file() or args.output.read_text() != text:
        args.output.write_text(text)
    print(f"variant table -> {args.output}")


if __name__ == "__main__":
    main()
